/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(foo.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(aa00dcfcfd70db1aad21fac61dbc42c0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/testcb/foo.h>
// pydoc.h is automatically generated in the build directory
#include <foo_pydoc.h>

void bind_foo(py::module& m)
{

    using foo    = gr::testcb::foo;


    py::class_<foo, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<foo>>(m, "foo", D(foo))

        .def(py::init(&foo::make),
           D(foo,make)
        )
        



        ;




}








